pipeline {
    agent any

    parameters {
        extendedChoice(
            name: 'BOARD',
            type: 'PT_CHECKBOX',
            groovyScript: '''
                def yamlFile = new File('/home/murtuza/Desktop/hardware_peripheral_testing/Peripheral_testing/boards.yaml')
                def boards = ['all']
                if (yamlFile.exists()) {
                    def content = yamlFile.text
                    def matcher = content =~ /(?m)^([a-zA-Z0-9_-]+):/
                    matcher.each { match -> boards.add(match[1]) }
                }
                return boards.unique().join(',')
            ''',
            defaultValue: 'all',
            multiSelectDelimiter: ' ',
            description: 'Select board(s) to test. Options are loaded dynamically from boards.yaml.'
        )
        extendedChoice(
            name: 'TEST_SUITE',
            type: 'PT_SINGLE_SELECT',
            groovyScript: '''
                def dir = new File('/home/murtuza/Desktop/hardware_peripheral_testing/Peripheral_testing')
                def tests = ['all']
                if (dir.exists()) {
                    dir.listFiles().each { file ->
                        if (file.name.startsWith('test_') && file.name.endsWith('.py')) {
                            tests.add(file.name)
                        }
                    }
                }
                return tests.join(',')
            ''',
            defaultValue: 'all',
            description: 'Select a specific test suite to run, or "all" to run everything.'
        )
        string(name: 'MODEL_NAME', defaultValue: 'google/gemma-4-26b-a4b-it:free', description: 'The LLM model to use for RCA and discovery.')
    }

    environment {
        // Inject OpenRouter API key securely from Jenkins Credentials
        OPENROUTER_API_KEY = credentials('OPENROUTER_API_KEY')
    }

    stages {
        stage('Setup Environment') {
            steps {
                sh '''
                    # Create and activate virtual environment
                    python3 -m venv venv
                    . venv/bin/activate
                    
                    # Install testing dependencies
                    pip install -r requirements.txt
                    
                    # Install AI Agent dependencies
                    pip install -r agent_requirements.txt
                '''
            }
        }
        
        stage('Execute Tests') {
            steps {
                // We use catchError to ensure the pipeline continues to the post block even if tests fail,
                // so that we can capture the .report.json and bsp_rca_report.md files.
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    sh '''
                        . venv/bin/activate
                        
                        # Handle 'all' test suite selection
                        TEST_ARG="${TEST_SUITE}"
                        if [ "$TEST_ARG" = "all" ]; then
                            TEST_ARG=""
                        fi
                        
                        # Run the BSP hardware validation tests
                        pytest ${TEST_ARG} --board ${BOARD} --json-report
                    '''
                }
            }
        }
    }

    post {
        always {
            // Archive the JSON report
            archiveArtifacts artifacts: '.report.json', allowEmptyArchive: true
            
            // Archive the Root Cause Analysis report generated by the autonomous agent
            archiveArtifacts artifacts: 'bsp_rca_report.md', allowEmptyArchive: true
        }
    }
}
