pipeline {
    agent any

    parameters {
        choice(name: 'BOARD', choices: ['auto', 'raspberry_pi_5'], description: 'Select the target board profile to validate.')
        string(name: 'MODEL_NAME', defaultValue: 'openai/gpt-4o', description: 'The LLM model to use for RCA and discovery.')
    }

    environment {
        // Inject OpenRouter API key securely from Jenkins Credentials
        OPENROUTER_API_KEY = credentials('OPENROUTER_API_KEY')
    }

    stages {
        stage('Setup Environment') {
            steps {
                sh '''
                    # Create and activate virtual environment
                    python3 -m venv venv
                    . venv/bin/activate
                    
                    # Install testing dependencies
                    pip install -r requirements.txt
                    
                    # Install AI Agent dependencies
                    pip install -r agent_requirements.txt
                '''
            }
        }
        
        stage('Execute Tests') {
            steps {
                // We use catchError to ensure the pipeline continues to the post block even if tests fail,
                // so that we can capture the .report.json and bsp_rca_report.md files.
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    sh '''
                        . venv/bin/activate
                        
                        # Run the BSP hardware validation tests
                        pytest --board ${BOARD} --json-report
                    '''
                }
            }
        }
    }

    post {
        always {
            // Archive the JSON report
            archiveArtifacts artifacts: '.report.json', allowEmptyArchive: true
            
            // Archive the Root Cause Analysis report generated by the autonomous agent
            archiveArtifacts artifacts: 'bsp_rca_report.md', allowEmptyArchive: true
        }
    }
}
